# Ask if there is some European country that reached 1 000 000 positive cases before the end of the 2020 except France
# Dataset: covid-world
# Usage: FILTER

prefix xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX voc: <http://www.example.org/vocabulary/>
PREFIX cw-voc: <http://www.example.org/covid-world/vocabulary/>

ASK
WHERE {
  SELECT ?obs ?posCases
  WHERE {
      ?obs rdf:type qb:Observation ;
          voc:refCountry ?country ;
          voc:refDate ?date ;
          cw-voc:cumulative-positive ?posCases .

      ?country rdf:type skos:Concept ;
          cw-voc:eu-country "true"^^xsd:boolean .

      FILTER ( ?posCases > 2000000 )
      FILTER ( year(?date) < 2021 )
      FILTER ( ?country != <http://www.example.org/covid-world/countries/FRA> )
  }
}